### ISSUE TITLE
Using contracts should not require installing js dependencies

### ISSUE THREAD

**Issue by JustynaBroniszewska** [OpenZeppelin/openzeppelin-sdk#1211]
Hi,

I want to use upgradability contracts but when I install `@openzeppelin/cli` or `@openzeppelin/upgrade` I install packages that I don’t really need (ethers, truffle, web3, loadsh). 

Could you extract solidity contracts to separate package that avoids javascript dependencies?

**Comment by jcarpanelli** [comment]
Hi, @JustynaBroniszewska! Thanks for bringing this up. We've been discussing about the project structure with the team lately, and this didn't come up, but it's a great idea IMO, as installing all those dependencies when just trying to use the upgradeability contracts could be somewhat cumbersome.

**Comment by nventuro** [comment]
We may move the contracts into the [`@openzeppelin/contracts`](https://github.com/OpenZeppelin/openzeppelin-contracts) repo soon, but even then, _some_ JavaScript (the OpenZeppelin CLI) is required/advised, since manually operating proxies is very dangerous. Tools are needed to properly set the implementation addresses, verify storage layout, call initializer functions, etc.

**Comment by JustynaBroniszewska** [comment]
Hey. Are there any updates on this?

**Comment by nventuro** [comment]
We're actually in the process of simplifying the Proxy architecture and migrating it to the contracts repo, but my previous point about requiring external tooling in order to safely use proxies still stands. 

Could you elaborate on your setup, and your use case for these contracts? Are you unable to use the tools in the OpenZeppelin SDK, or finding them lacking?

**Comment by spalladino** [comment]
Closing in favor of #1314
