### ISSUE TITLE
Error during Verify

### ISSUE THREAD

**Issue by euazzo** [OpenZeppelin/openzeppelin-sdk#1278]
Error during contract verification:
`Error while trying to verify contract: Fail - Unable to verify`

zos version: _2.4.2_

Smart contract:
![image](https://user-images.githubusercontent.com/57409287/68228420-b299b900-fff5-11e9-86f9-83c02b9f4490.png)

Operations:
![image](https://user-images.githubusercontent.com/57409287/68228110-225b7400-fff5-11e9-819e-b054bd0c6c8d.png)

**Comment by abcoathup** [comment]
Hi @euazzo,

I previously had an issue with verify, that I resolved by explicitly compiling with optimizer disabled:
https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1183#issuecomment-521953370

You may also want to upgrade to `@openzeppelin/cli`.

For support questions it is generally best to ask in the OpenZeppelin Community Forum as then the entire community can help answer your question rather than just those watching the repository: 
https://forum.openzeppelin.com/

**Comment by euazzo** [comment]
Hi @abcoathup, 

I have tried to disable the optimizer and now it works.
Thank you for the support.
