### ISSUE TITLE
Add CONTRIBUTING.ko.md with korean

### ISSUE THREAD

**Issue by skqksh** [OpenZeppelin/openzeppelin-sdk#1353]
I hope korean developers also know this awesome sdk and contribute

so. I want to add contribute guide with korean

Could I add CONTRIBUTING.ko.md

**Comment by abcoathup** [comment]
Hi @skqksh,

Thank you!  I am the Community Manager at OpenZeppelin.
I think a guide on how to contribute in Korean posted in the community forum could be great: https://forum.openzeppelin.com/ 
I think maintaining a document in a language other than English in the repository could be a challenge, so the forum seems like a better place to put this.  It can be a wiki post so that anyone can edit and update.

What could be really awesome would be to translate some of the guides for using the SDK and post in the forum (along with relevant web3 developer communities with Korean speakers) and we can also share on social media.

Some of the following guides could be good, though would be guided by you on what would be most useful (and also fun to create):
* [Your first project](https://docs.openzeppelin.com/sdk/2.6/first)
* [Deploy your contracts to a public network](https://docs.openzeppelin.com/sdk/2.6/public-deploy)
* [Building an OpenZeppelin Network.js powered dapp from scratch](https://docs.openzeppelin.com/sdk/2.6/network-js)

Another option would be to create a starter kit in Korean to help developers get up and running with dapps using the tools: https://docs.openzeppelin.com/starter-kits/2.3/create

Also creating some guides of Ethernaut levels (or translating existing ones) would be great too: https://forum.openzeppelin.com/t/ethernaut-community-solutions/561

Let me know how I can help.

**Comment by skqksh** [comment]
@abcoathup 

Thanks for explanation.

Let me try to translate that in korean from 'Your first project'

But I wonder how to start and commit what I translated

**Comment by abcoathup** [comment]
Hi @skqksh,

That sounds fantastic.
The markdown for the original is here: https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/docs/modules/ROOT/pages/first.adoc

Depending on whatever is easier for you, you could:
* Create a post in https://forum.openzeppelin.com/c/general/guides-and-tutorials/23 and I will change to be a wiki and you can work on it directly there.
* Create in markdown and post to the forum when you are ready

Let me know how I can help.  Thanks again.

**Comment by abcoathup** [comment]
Hi @skqksh,

Thank you so much for doing the translation :pray:

The original document is in ASCII doc, whilst the forum is in markdown (apologies, I said the original was in markdown).

I changed the formatting from ASCII doc to markdown.  I checked the text by converting back to English and it looked ok.
https://forum.openzeppelin.com/t/korean-openzeppelin-sdk-your-first-project/1966

If you can, it would be great to see if a Korean speaker can follow the guide and what questions they have.  

Would you like to do more translations?  
It would be great to translate:
[Deploy your contracts to a public network](https://docs.openzeppelin.com/sdk/2.6/public-deploy)

**Comment by skqksh** [comment]
Hi. Andrew

It's good that you talk to me what should I translate for next


ᐧ

2019년 12월 23일 (월) 오전 10:52, Andrew B Coathup <notifications@github.com>님이
작성:

**Comment by abcoathup** [comment]
Hi @skqksh,

(If you have the time and interest) It would be great to translate:
[Deploy your contracts to a public network](https://docs.openzeppelin.com/sdk/2.6/public-deploy)

That way, Korean speaking community members can create a contract and deploy to a public network.
