### ISSUE TITLE
Design choice between upgradeable and regular deploys

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1377]
As part of #802, we need to define how a user will choose whether a new contract will be upgradeable or not.

**Comment by spalladino** [comment]
My thoughts on this: 

Asking on project initialization, as @frangio had mentioned, may not be a good idea, since we may be dropping the need for `oz init` altogether in v3. Also, the choice seems to be tied to the network where the user is working, so it does not make sense to ask for a project-wide default.

With that in mind, I'd ask the user upon `oz deploy`. However, there are a few decisions to make:

### Upgradeable Yes/No vs Regular/Upgradeable/Minimal

We can ask the user whether they want the deploy to be upgradeable or not (a Y/N question), or on _kind_ of deployment (regular, upgradeable, minimalproxy). While the first is more straightforward, the second can help making the minimal proxy more available. We can think of rephrasing it to "repeatable" or "multiple" deploy, instead of "minimal".

### Ask again vs Require flag to change

After the user has chosen the kind of deployment (for a specific network), we can either 1) keep asking the same question on every `deploy` (though defaulting to the last answer, as we do with networks), or 2) assume that all contracts in the same network will have the same deployment kind, and require a flag to override.

Given that users that work with interactivity may not be familiar with the flags, I'd go with (1), even if we are making the creation process a bit more complex (though defaulting to last answer should ameliorate this).

### Network vs Network & Contract

While we should ask _after_ the choice of network (so we can tie the decision to the network), we can ask before or after the choice of contract to deploy. This depends on whether we think if a user will want to have regular and upgradeable contracts on the same project and the same network (which we know is the case for some complex projects). 

This would impact on the criteria for choosing the default (or assumed, depending on the previous section) deployment kind. We would need to store the last deployment choice per network & contract, as well as the last choice for the network overall (to use as a default for contracts deployed for the first time in that network), *or* the last choice for the contract overall (to use as a default for a deployment of that contract in a new network).

Here I'd just remember the last choice per-network, as it's easier to implement, and probably easier for the user to grasp the criteria.

**Comment by frangio** [comment]
I agree on asking for "kind" rather than yes/no. I'm not sure about using "multiple" for "minimal", because I think people are already familiar with the "minimal proxy" name (are they?); perhaps we can put it in parentheses or something.

I think there is ambiguity in the term "default", we use it in opposite ways. To me, a parameter having a default value means that we won't interactively ask about it, and the only way to change it is via CLI flags, such as `--verbose`. The other meaning for default I would call a "preselection" during the interactive flow. It's really important not to confuse these two things, particularly because we have `--no-interactive`, and our choice for a preselection is probably not the same as a choice for default behavior!

There may also be cases where we want a default behavior if interactivity is disabled, but we do want to ask if in the interactive flow. There's certainly cases like this in the current CLI design, but I would try to keep them to a minimum for simplicity. What do you think? I can think of sessions and I think also the `--from` option is in this category? I'm not sure how I feel about these cases.

My intuition is that defaults should never change dynamically, unless the user asks for it explicitly (e.g., if the options are "yes/no/always"). The reasoning is that we want the tool to behave predictably without a complex mental model. Arguably, preselections also harm predictability, but only for pressing Enter through the interactive prompts, which I think is a good trade-off for when this does come in handy.

Based on the argument of avoiding complex mental models for tool behavior, I agree that basing the preselection only on the network and not on the contract choice is better.

What should the behavior be "kind" be for non-interactive usage of deploy? Do we want to force the user to specifiy it via a flag, or do we want it to have a default? Should it be in the category of "has a default but we ask during interactivity"?

**Comment by spalladino** [comment]
> I think there is ambiguity in the term "default", we use it in opposite ways. To me, a parameter having a default value means that we won't interactively ask about it, and the only way to change it is via CLI flags, such as --verbose. The other meaning for default I would call a "preselection" during the interactive flow. It's really important not to confuse these two things, particularly because we have --no-interactive, and our choice for a preselection is probably not the same as a choice for default behavior!

Good point. I was talking about `defaults` in the sense of preselection, but I like your definitions more.

> What should the behavior of "kind" be for non-interactive usage of deploy? Do we want to force the user to specifiy it via a flag, or do we want it to have a default? Should it be in the category of "has a default but we ask during interactivity"?

It's a good question. I think I'd always require it, even if it's a PITA - but it's a very critical setting to just assume. WDYT?

**Comment by frangio** [comment]
Yeah, I also think we should require it.

**Comment by frangio** [comment]
This has been implemented as agreed on the comments above in the new `oz deploy` command that will be released in 2.8.
