### ISSUE TITLE
Fails to send funds from one contract to another.

### ISSUE THREAD

**Issue by tsudmi** [OpenZeppelin/openzeppelin-sdk#1444]
Hi,

I get a `Error: Error: Returned error: VM Exception while processing transaction: revert` when calling `transfer` from one contract to another.

Here is a reproducible example:

ContractA.sol:
```solidity
pragma solidity 0.6.2;

import "@openzeppelin/upgrades/contracts/Initializable.sol";

contract ContractA is Initializable {
    address private admin;

    function initialize(address _admin) public initializer {
        admin = _admin;
    }

    receive() external payable { }
}
```
ContractB.sol:
```solidity
pragma solidity 0.6.2;

import "@openzeppelin/upgrades/contracts/Initializable.sol";
import "./ContractA.sol";

contract ContractB is Initializable {
    ContractA private contractA;

    function initialize(ContractA _contractA) public initializer {
        contractA = _contractA;
    }

    function withdraw() external payable {
        payable(address(contractA)).transfer(msg.value);
    }
}
```

It will revert on `withdraw` function call of `ContractB`.

### Environment:
ganache-cli: 6.9.0
openzeppelin/cli: 2.7.0
openzeppelin/upgrades: 2.7.0

**Comment by abcoathup** [comment]
Hi @tsudmi,

This is due to the changes in Istanbul.

The following posts in the forum may be useful:
https://forum.openzeppelin.com/t/openzeppelin-upgradeable-contracts-affected-by-istanbul-hardfork/1616
https://forum.openzeppelin.com/t/reentrancy-after-istanbul/1742

Please post this question in the Community Forum with a link to this Issue: https://forum.openzeppelin.com/c/support/17

Questions are best asked in the Community Forum so that anyone in the community can help you.  I will close this Issue and we can continue answering your question in the Forum.

**Comment by abcoathup** [comment]
Hi @tsudmi,

I posted your question to the Community Forum along with an answer: https://forum.openzeppelin.com/t/fails-to-send-funds-from-one-contract-to-another/2267
