### ISSUE TITLE
Docs have wrong return type when tuples

### ISSUE THREAD

**Issue by ilanolkies** [OpenZeppelin/openzeppelin-sdk#1530]
Hi!

I think the Smart Contract API docs are wrong when showing tuple returns:

https://github.com/OpenZeppelin/openzeppelin-sdk/blob/c68234271a4a6e29b989fe1bac1902a246a298b3/packages/lib/docs/modules/ROOT/pages/api.adoc#getpackagestring-packagename--contract-package-var-typeuint643-item-kindpublic

Thanks,

**Comment by frangio** [comment]
Hi @ilanolkies! Thanks for reporting. This is a bug we've fixed in Contracts and haven't ported here yet.

However, this file shouldn't be in the repo in the first place. :slightly_smiling_face: It's generated in the docs build, and you should view it at [docs.openzeppelin.com/upgrades/api](https://docs.openzeppelin.com/upgrades/api).

**Comment by frangio** [comment]
Removed the file in 427fc2ce4305892459aca713f46d9f810ff24087, and fixed the template in f6e3f09efece6c2a36a6c48f982099f9948c1521.
