### ISSUE TITLE
Modify CLI commands to work lib contracts as an on-chain library

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#90]
Once we have moved all the lib contracts to an on-chain library (see https://github.com/zeppelinos/zos-lib/issues/224), our current commands being supported by the CLI should be modified to support such change. 

Here are some things that we may want to consider that also follow the lightweight idea:
- `add` could keep working as it is doing currently
- `push` could upload all the implementations to a network and the respective addresses could be saved of-chain in the `zos.<network>.json` file by default
- `create` could work picking the addresses of the implementations from the `zos.<network>.json` file by default
- `upgrade` could work picking the addresses of the implementations from the `zos.<network>.json` file by default. 
- `bump` could only modify the version of the `zos.<network>.json` file working as an of-chain piece of information.
- we can work on a new `publish` or so command that simply deploys the whole lib architecture to the network updating the  `zos.<network>.json` file with the respective addresses of the app and package contracts
- Finally, I think there are two options... either the `push`, `create` and `update` could start using the on-chain `App` information once the whole architecture has been deployed (once the `publish` command has been run), or they can still work the same way and you need to run the `publish` command to reflect whatever the `zos.<network>.json` has locally to the on-chain representation of your app.

I'm sure there are a lot of many other edge cases here that we will need to keep thinking on, but I'm leaving this idea to start discussing the topic.

**Comment by spalladino** [comment]
I feel like we're mixing up two things here: lightweight mode for the CLI, and upgradeable zOS contracts. IMO these are two different topics. 

1- Upgradeable zOS contracts can be implemented using https://github.com/zeppelinos/zos-lib/issues/224, and the only changes required are actually having the `push` command create a proxy to App/Package/Provider instead of deploying new ones. There is an extra complication which arises from who `admin`s these proxies (should we transfer upgradeability ownership of the App to the App itself? it may require a forwarding contract in between).

2- Lightweight mode for the CLI would imply changing the commands as discussed in the issue. This is, instead of registering all implementations in a Provider on-chain, just keep all that info off-chain in the network.json files, and work from them.

**Comment by facuspagnuolo** [comment]
True, I was considering that both issues could be tackled at once. Given that the `push` command needs to change in different ways depending on which feature we implement first, IMO it will be more straightforward to adapt the CLI to the lightweight mode and then make it work with the on-chain libraries than the other way around. But of course, we can first implement the lightweight mode moving the `App` architecture deployment to the `publish`-like command and then make it work with proxies.

Let's discuss a little bit which one we should tackle first and then I'll update the issues with the final decission

**Comment by spalladino** [comment]
Closing as lightweight mode has been implemented, and #1325 covers the other half
